# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Colorful' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Colorful
pod 'Alamofire', '~> 4.8.2'
pod 'Kingfisher', '~> 5.0'

  target 'ColorfulTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ColorfulUITests' do
    # Pods for testing
  end

end
